version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: bharat-id-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: bharatadmin
      MONGO_INITDB_ROOT_PASSWORD: sovereign2026
      MONGO_INITDB_DATABASE: bharatid
    volumes:
      - mongodb_data:/data/db
    networks:
      - bharat-network

  redis:
    image: redis:7.2-alpine
    container_name: bharat-id-redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass sovereign2026
    volumes:
      - redis_data:/data
    networks:
      - bharat-network

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  bharat-network:
    driver: bridge
